### ISSUE TITLE
New firmware 9.0.D

### ISSUE THREAD

**Issue by JoelLinn** [xdarklight/lantiq-xdsl-firmware-info#30]
https://download.avm.de/fritzbox/fritzbox-7430/deutschland/fritz.os/FRITZ.Box_7430-07.21.image

extract like any other avm firmware

```
filename: vr9-A-dsl.bin
version: 5.9.1.4.0.7-5.9.0.D.0.1
sha1sum: 41375044e876fe971007c469a96b89a5937610d7
filesize: 927096
Firmware1:
        PLATFORM: 5
        PLATFORM_STR: VRX200
        APPLICATION_TYPE: 7
        APPLICATION_TYPE_STR: VDSL over ISDN incl. vectoring support
        VERSION_STR: 9.1.4
        RELEASE_STATUS: 0
        RELEASE_STATUS_STR: Release
Firmware2:
        PLATFORM: 5
        PLATFORM_STR: VRX200
        APPLICATION_TYPE: 1
        APPLICATION_TYPE_STR: ADSL Annex A
        VERSION_STR: 9.0.D
        RELEASE_STATUS: 0
        RELEASE_STATUS_STR: Release

vr9-A-dsl.bin.bsdiff: NO firmware versions found - is this a valid lantiq DSL firmware file?
filename: vr9-B-dsl.bin
version: 5.9.1.4.0.7-5.9.0.D.0.2
sha1sum: ab8aeaf0894643356fa66a87304f388f43ee31e3
filesize: 908888
Firmware1:
        PLATFORM: 5
        PLATFORM_STR: VRX200
        APPLICATION_TYPE: 7
        APPLICATION_TYPE_STR: VDSL over ISDN incl. vectoring support
        VERSION_STR: 9.1.4
        RELEASE_STATUS: 0
        RELEASE_STATUS_STR: Release
Firmware2:
        PLATFORM: 5
        PLATFORM_STR: VRX200
        APPLICATION_TYPE: 2
        APPLICATION_TYPE_STR: ADSL Annex B
        VERSION_STR: 9.0.D
        RELEASE_STATUS: 0
        RELEASE_STATUS_STR: Release

```
